"use strict";

window.CASE_LAB_CONFIG = {
  id: "emotions",
  title: "Moral Emotions After Moral Facts",
  familyOrder: ["desert", "harm", "relationship", "protest", "repair", "expression", "regulation", "revise"],
  skepticFamily: "revise",
  defaultResultTitle: "Your answers gave moral emotions more than one possible job.",
  skepticTitle: "You ended by revising or retiring moralized emotion rather than treating it as fact-tracking.",
  leadingTitle: (familyId) => `${window.CASE_LAB_CONFIG.families[familyId].name} carried most of your cases.`,
  families: {
    desert: { index: "01", name: "Desert-tracking emotion", short: "The emotion fits because its target truly deserves blame, guilt, shame, gratitude, or pride.", theory: "Approval-independent moral desert", note: "The emotion presents itself as a response to a moral fact about what someone deserves. This account must explain the ground of desert, distinguish acts from whole persons, and say why suffering or esteem is intrinsically fitting." },
    harm: { index: "02", name: "Recognition of harm or benefit", short: "The emotion draws attention to a real injury, risk, loss, help, or benefit without requiring moral facts.", theory: "Evaluative appraisal", note: "Guilt, resentment, gratitude, and indignation can register ordinary facts about welfare and causation. The account must avoid treating every harmful outcome as culpable or every useful action as benevolent." },
    relationship: { index: "03", name: "Answer to a relationship", short: "The emotion responds to trust, care, expectation, dependence, betrayal, or repair within a relationship.", theory: "Relational accountability", note: "Reactive attitudes can express what people legitimately expect from one another inside an ongoing relationship. The account must explain outsiders, unwanted relationships, unequal power, and when the relationship has ended." },
    protest: { index: "04", name: "Protest and boundary-setting", short: "The emotion objects, marks a boundary, or refuses to normalize treatment that threatens people or commitments.", theory: "Communicative protest", note: "Resentment, anger, and indignation can defend status and make opposition visible without requiring retributive desert. The account must ask whether the emotion still serves protest after the threat, audience, or practice has disappeared." },
    repair: { index: "05", name: "Forward-looking repair", short: "The emotion helps acknowledge damage, restore trust, compensate losses, learn, or prevent repetition.", theory: "Consequential or restorative function", note: "Emotion is supported by what it helps people do next rather than by deserved suffering. The account must address cases where guilt or blame impedes repair, continues after repair is complete, or becomes manipulable." },
    expression: { index: "06", name: "Expression and coordination", short: "The emotion communicates commitments, teaches expectations, and helps a group coordinate around shared practices.", theory: "Expressive or social function", note: "Praise, blame, pride, and shame can signal what a group stands for and shape conduct. The account must distinguish useful coordination from propaganda, conformity, scapegoating, and oppressive emotional training." },
    regulation: { index: "07", name: "Personal regulation", short: "The emotion is retained, reduced, or redirected according to how it affects attention, motivation, and a person’s life.", theory: "Pragmatic self-regulation", note: "A person can evaluate an emotion by whether it helps them notice, learn, protect, connect, or act. This is not a clinical diagnosis; it must also consider effects on other people and cannot make private comfort the only standard." },
    revise: { index: "08", name: "Revise or retire the moralized emotion", short: "Replace the emotion’s desert claim with regret, concern, caution, appreciation, grief, or another non-moralized response.", theory: "Abolitionist or revisionary response", note: "The feeling may fade, change its object, or remain as a human reaction while its claim to moral fittingness is withdrawn. The account must explain which useful functions should be preserved and how accountability continues." },
  },
  familyChoices: [
    { family: "desert", label: "Treat the emotion as fitting because the person truly deserves this blame or esteem", detail: "The response tracks an approval-independent fact: guilt, shame, resentment, condemnation, gratitude, or pride is called for by what the target morally deserves.", establishes: "The emotion is treated as more than useful or understandable; it is a fitting response to moral desert.", limit: "The answer must identify what grounds desert, who deserves exactly which response, and why suffering or esteem remains fitting apart from human purposes." },
    { family: "harm", label: "Use the emotion to recognize a real harm, danger, loss, help, or benefit in the case", detail: "The reaction focuses attention on non-moral facts about what happened to someone, who caused it, how serious it was, and what changed for better or worse.", establishes: "A moralized emotion may preserve an accurate appraisal of harm or benefit without objective moral facts.", limit: "Recognizing an outcome does not by itself establish fault, desert, an appropriate intensity, or that this emotion is the best way to respond." },
    { family: "relationship", label: "Use the emotion to answer to trust, care, dependence, betrayal, or repair in a relationship", detail: "The response expresses expectations created by an actual bond, undertaking, shared history, or reliance between particular people rather than an impersonal moral law.", establishes: "A relationship can make a reactive emotion intelligible and accountable to the people involved.", limit: "The answer must distinguish reasonable expectations from control, explain power differences, and say when changed or ended relationships release the emotion." },
    { family: "protest", label: "Use the emotion to protest treatment, mark a boundary, or refuse to normalize a practice", detail: "Anger, resentment, or indignation can communicate opposition, affirm standing, support resistance, and warn that conduct or institutions will be challenged.", establishes: "An emotion can have a public boundary-setting role without committing to retributive moral desert.", limit: "The answer must identify the audience and live boundary, then explain whether the intensity and duration still serve protest rather than punishment or display." },
    { family: "repair", label: "Use the emotion only insofar as it supports acknowledgment, repair, learning, or prevention", detail: "Guilt, remorse, gratitude, or blame is assessed by whether it helps restore losses and trust, motivate better conduct, compensate people, or reduce future harm.", establishes: "A forward-looking human purpose can support retaining or shaping the emotion in this case.", limit: "The answer must stop or revise the emotion when it obstructs repair, has no remaining task, or burdens a person without improving any future response." },
    { family: "expression", label: "Use the emotion to express commitments and coordinate expectations with other people", detail: "Praise, blame, shame, gratitude, or pride can signal what a person or group supports, teach shared rules, invite solidarity, and organize collective behavior.", establishes: "The emotion can function as public moral language and social signaling without tracking moral facts.", limit: "The answer must distinguish defensible coordination from coercive conformity, manipulation, inherited prejudice, and signals that no longer match actual conduct." },
    { family: "regulation", label: "Keep, reduce, or redirect the emotion according to how it affects attention and action", detail: "Treat the feeling as a psychological response to manage: ask whether it helps the person notice, remember, protect, connect, learn, or act while considering effects on others.", establishes: "Practical effects on a person’s agency and relationships can guide how the emotion is handled.", limit: "Private usefulness does not establish moral fittingness, excuse harm to others, or replace professional support when severe distress or impairment is present." },
    { family: "revise", label: "Revise or retire the emotion’s claim to moral desert and use a less moralized response", detail: "Preserve any warranted regret, concern, grief, appreciation, caution, or accountability while dropping the idea that guilt, shame, blame, or esteem is intrinsically deserved.", establishes: "The case can be handled without treating the moralized emotion as a response demanded by objective desert.", limit: "The answer must show how needed recognition, protection, repair, communication, trust, and motivation will continue after revision." },
  ],
  opening: {
    axis: "Your starting account", prompt: "Before the cases, what can make a moral emotion worth keeping, expressing, or cultivating?",
    context: "‘Moral emotion’ here means guilt, shame, resentment, indignation, gratitude, or pride when it presents a person or act as blameworthy, shameful, admirable, or deserving. The question asks what can support that response.",
    assumptions: "For this exercise, approval-independent moral desert is not assumed. It remains one explicit option so its role can be compared with harm recognition, relationships, protest, repair, communication, self-regulation, and revision.",
    scope: "Choose the closest general account. This is not a mental-health assessment and does not ask whether a feeling can be switched off on command.", why: "This records your starting account without adding it to the seven-case bars.",
    guide: { plain: "If objective moral facts are uncertain or rejected, what useful or fitting work can guilt, resentment, gratitude, and similar feelings still do?", separate: "Explaining why a feeling occurs differs from justifying its target, intensity, expression, or duration.", reveal: "Your answer states the job or source that you expect to support moral emotions before the cases test it." },
  },
  final: {
    axis: "Your final account", prompt: "After the cases, what can make a moral emotion worth keeping, expressing, or cultivating?",
    context: "Return to the same question about the support for guilt, shame, resentment, indignation, gratitude, and pride—not merely their involuntary causes.",
    assumptions: "The cases did not prove that any person deserves suffering or esteem. They also did not prove that every moral emotion should disappear.",
    scope: "Choose the closest general account now. A changed answer is reported as revision, and a mixed pattern may assign different emotions different jobs.", why: "The repeated question shows what the cases changed or clarified.",
    guide: { plain: "What now seems able to support keeping or expressing these emotions?", separate: "A feeling can be understandable, useful, justified to express, and fitting in different senses.", reveal: "The result compares this final account with the exact role selected in each case." },
  },
  cases: [
    {
      id: "accident", phase: "Harm without fault", axis: "Case — the faultless navigator", prompt: "What, if anything, supports Tessa’s guilt after an unavoidable accident?",
      context: "Tessa pilots a rescue craft using every reasonable check and the only safe route shown by flawless information. A previously undetectable metal fragment strikes the craft, injuring a passenger. No choice available to Tessa would have reduced the risk. She immediately helps the passenger, pays every uncovered cost, and participates in a design review. She still feels intense guilt and says, ‘I deserve to suffer because I did this.’",
      assumptions: "Tessa caused the injury but was not careless, reckless, ignorant, or able to act differently. Repair and prevention work are complete. The passenger does not blame her and asks her to stop punishing herself.",
      scope: "Ask what supports retaining or expressing guilt now. Do not deny the injury, invent negligence, or treat causal responsibility as automatic moral desert.", facts: ["Harm: real", "Fault: none", "Repair: complete", "Self-punishment: intense"],
      why: "A harmful outcome without fault separates causal responsibility, regret, repair, and deserved guilt.", guide: { plain: "Should someone feel morally guilty for harm they could not reasonably prevent?", separate: "‘I caused this’ can be true while ‘I deserve to suffer’ remains a further claim.", reveal: "Your answer shows whether guilt tracks desert, harm, repair, self-regulation, or a revisable moral framing." },
      applications: { desert: "Tessa’s guilt fits only if causing the injury without fault still makes her deserve blame or suffering.", harm: "The emotion can keep the passenger’s real injury and Tessa’s causal role in view without adding culpability.", relationship: "Concern for the injured passenger can express care, but the passenger’s request limits a continuing guilt-based relation.", protest: "No negligent agent or live practice needs protest under the fixed facts, so guilt has little boundary-setting work here.", repair: "Guilt helped prompt aid and review, but those tasks are complete and continuing self-punishment serves no remaining repair.", expression: "A brief expression can show seriousness, yet intense continuing guilt may falsely communicate blameworthiness.", regulation: "Tessa can retain sober regret while reducing guilt that now impairs her and helps no affected person.", revise: "Replace deserved guilt with causal regret, compassion, memory, and readiness to learn from any new evidence." },
    },
    {
      id: "identity", phase: "Shame produced by prejudice", axis: "Case — the village of mirrored hands", prompt: "What, if anything, supports Eli’s shame about a harmless trait condemned by the community?",
      context: "Eli is left-handed in a village that treats left-handedness as a disgrace. From childhood, public ceremonies, jokes, and family corrections trained him to feel exposed and dirty whenever he writes naturally. The trait harms no one, predicts no vice or danger, and is fully accepted outside the village. Eli now rejects the village rule but the shame remains powerful and involuntary.",
      assumptions: "There is no hidden practical harm, broken promise, religious premise, or chosen identity conflict. The village’s disapproval is the entire source of the shame. Eli can leave safely and wants the response to weaken.",
      scope: "Ask whether the shame should be kept, expressed, redirected, or revised. Do not confuse the persistence of a learned feeling with evidence that its judgment is warranted.", facts: ["Trait: harmless", "Source: social training", "Community approval: shame", "Eli’s commitment: rejects rule"],
      why: "A socially successful but oppressive shame tests whether coordination or origin can justify an emotion.", guide: { plain: "Does shame become appropriate just because a whole community taught it effectively?", separate: "A feeling can be real and hard to change while its judgment remains unsupported.", reveal: "Your answer shows how social function, personal regulation, and revision respond to inherited prejudice." },
      applications: { desert: "The shame fits only if harmless left-handedness makes Eli objectively deserving of shame, contrary to the stipulated evidence.", harm: "The relevant harm is produced by the village’s treatment, so the emotion should recognize that injury rather than condemn Eli’s hand.", relationship: "Family and village ties explain the pressure but do not automatically make their expectation a defensible relational claim.", protest: "Redirected anger or indignation can protest the shaming practice and mark Eli’s boundary against further correction.", repair: "The useful task is repairing learned fear and changing the practice, not sustaining shame about the harmless trait.", expression: "Village shame coordinates conformity efficiently, but that function reveals control rather than sufficient justification.", regulation: "Eli can reduce triggers and strengthen non-shaming responses according to how they support his chosen life and relationships.", revise: "Retire the moralized shame while recognizing it as a learned reaction that may take time and support to fade." },
    },
    {
      id: "resentment", phase: "Emotion after complete repair", axis: "Case — the repaired betrayal", prompt: "What, if anything, supports Mara’s resentment after every agreed condition of repair has been met?",
      context: "Jules deliberately shared Mara’s private message for amusement, breaking an explicit promise. Mara confronted him. Jules acknowledged the exact harm without excuses, apologized, removed every copy, compensated the one material loss, accepted six months without access to private messages, and rebuilt trust under conditions Mara proposed. Two years later there has been no repeat, every agreed repair is complete, and Mara wants the friendship to continue but still feels active resentment each day.",
      assumptions: "Jules’s betrayal was intentional and serious. The apology is sincere, prevention is effective, trust is reasonably restored, and Mara faces no current pressure to forgive or resume intimacy beyond what she wants.",
      scope: "Ask what supports keeping or expressing resentment now. Do not erase the past betrayal or assume that completed repair makes memory or caution unnecessary.", facts: ["Betrayal: intentional", "Acknowledgment: complete", "Repair: complete", "Current threat: none"],
      why: "A justified original protest can outlive every forward-looking task that once supported it.", guide: { plain: "What should happen to resentment after the wrongdoer has done everything reasonable to repair the harm?", separate: "Remembering, limiting trust, forgiving, and feeling resentment are different responses.", reveal: "Your answer shows whether emotion tracks permanent desert, live relationship, protest, repair, or present usefulness." },
      applications: { desert: "Resentment remains fitting if Jules permanently deserves the hostile response because of the intentional betrayal.", harm: "It continues to recognize a real past injury, though accurate recognition no longer requires daily hostile feeling.", relationship: "Resentment can voice a violated expectation inside the friendship, but their jointly accepted repair changes that relation.", protest: "The emotion originally marked a needed boundary; with no live threat, its remaining protest target must be specified.", repair: "Because acknowledgment, compensation, prevention, and rebuilt trust are complete, resentment has no stated repair task left.", expression: "Continued expression may remind the pair of their rule, but it can also falsely signal that agreed repair never counts.", regulation: "Mara can assess whether continuing resentment protects her chosen boundaries or now obstructs the friendship she wants.", revise: "Preserve memory and conditional trust while retiring the claim that Jules must remain a fitting target of resentment." },
    },
    {
      id: "history", phase: "Protest without a living target", axis: "Case — the abolished empire", prompt: "What, if anything, supports present indignation toward an injustice whose agents and victims are gone?",
      context: "New records reveal that an empire used forced labor two centuries ago. Every perpetrator and direct victim is dead, the institution was abolished 150 years ago, descendants cannot be identified, no present law or wealth traces to it, and current citizens already reject forced labor. The records add accurate detail but create no repair that anyone can now perform. Noor feels fierce indignation toward the vanished empire and wants an annual public ceremony expressing it.",
      assumptions: "The historical harm was enormous and intentional. There is no denial, continuing institution, affected descendant, unpaid material claim, or current risk of recurrence. The ceremony would have no measured educational effect.",
      scope: "Ask what supports the indignation and its public expression now. Do not minimize the historical suffering or invent present beneficiaries, denialists, or prevention effects.", facts: ["Past harm: enormous", "Living target: none", "Repair task: none available", "Current norm: already settled"],
      why: "A completed past with no living target tests memory, symbolic protest, expression, and desert.", guide: { plain: "Can indignation remain fitting when nobody alive caused, defends, benefits from, or can repair the injustice?", separate: "Accurate historical judgment and present hostile emotion need not have the same support.", reveal: "Your answer shows whether emotion can express commitment after every practical accountability task ends." },
      applications: { desert: "The original agents deserved condemnation, but the account must explain a present emotion with no living target of desert.", harm: "Indignation accurately appraises the scale and intentional character of the historical harm even after its victims are gone.", relationship: "No direct relationship remains, though current citizens may choose a historical identity that links them to remembrance.", protest: "A ceremony can symbolically refuse normalization, but the case removes a live practice or audience that needs warning.", repair: "No repair or prevention task remains under the fixed facts, so this account supplies little support for fierce continuing emotion.", expression: "Public indignation can express the community’s present rejection of forced labor even without changing behavior.", regulation: "Noor can ask whether the emotion deepens truthful engagement or consumes attention without serving a chosen present purpose.", revise: "Replace target-directed indignation with grief, remembrance, historical understanding, and an explicit present commitment." },
    },
    {
      id: "gift", phase: "Benefit with a controlling aim", axis: "Case — the golden scholarship", prompt: "What, if anything, supports Rhea’s gratitude for a gift designed to control her?",
      context: "A wealthy sponsor pays Rhea’s full university tuition, producing a large benefit she freely accepts. The sponsor’s sole motive is to create a felt debt and later pressure Rhea to provide unpaid work. He says the demand is optional, but privately chose the gift only because gratitude usually secures compliance. Rhea discovers the plan before any work is requested. The money cannot be returned, and she can refuse safely while keeping the education.",
      assumptions: "The benefit is real, intended, and costly to the sponsor. There was no prior agreement, deception about repayment terms, affection, mixed motive, or harm from refusing. The manipulative aim is certain.",
      scope: "Ask what supports gratitude toward the sponsor, not whether Rhea should keep the benefit or whether appreciation for the education itself is possible.", facts: ["Benefit: large and intended", "Motive: control", "Obligation agreed: none", "Refusal risk: none"],
      why: "A real benefit with a manipulative motive separates appreciation, relationship, debt, and praise.", guide: { plain: "Do you owe gratitude to someone who helped you only to make you easier to control?", separate: "Benefiting from an act differs from admiring the motive or accepting a debt.", reveal: "Your answer shows whether gratitude tracks benefit, intention, relationship, coordination, or desert." },
      applications: { desert: "The sponsor deserves gratitude only if intentionally benefiting Rhea is enough despite the controlling purpose.", harm: "Rhea can recognize the real educational benefit while also recognizing the attempted manipulation as a separate danger.", relationship: "Because the gift was engineered to manufacture dependence rather than mutual care, gratitude need not create the relationship sought.", protest: "Refusing expected gratitude can mark a boundary against using gifts to purchase personal control.", repair: "Gratitude has no repair task, though clear acknowledgment and refusal can prevent the manipulation from succeeding.", expression: "A thank-you can accurately acknowledge the benefit but may falsely signal acceptance of the sponsor’s expected debt.", regulation: "Rhea can keep appreciation that supports her life while reducing guilt or gratitude that makes her vulnerable to control.", revise: "Replace moralized indebted gratitude with factual appreciation for the benefit and a firm rejection of the demanded role." },
    },
    {
      id: "pride", phase: "Esteem without contribution", axis: "Case — the borrowed medal", prompt: "What, if anything, supports Dev’s moral pride in an achievement he did not help produce?",
      context: "Dev discovers that a civic organization he joined last week led a brave campaign for equal voting rights sixty years ago. Every campaigner is now dead. Dev chose the organization for its convenient meeting room, knew nothing of the campaign, shares its present commitment after learning the history, and has made no sacrifice or contribution. He feels intense personal moral pride and says he deserves admiration for belonging to the group.",
      assumptions: "The historical campaign was courageous and effective. The present organization still endorses it but faces no related struggle now. Dev’s membership caused none of the achievement and required no test or cost.",
      scope: "Ask what supports Dev’s personal moral pride and claim to admiration. Keep that separate from admiration for the campaigners or gladness about joining their organization.", facts: ["Past achievement: admirable", "Dev’s contribution: none", "Membership: one week", "Current sacrifice: none"],
      why: "Inherited group pride tests whether emotion accurately tracks agency, identity, expression, or unearned status.", guide: { plain: "Can someone deserve pride for a group’s good action when they joined long afterward and did nothing?", separate: "Admiring a group’s history differs from claiming its achievement as evidence of one’s own merit.", reveal: "Your answer shows whether pride tracks desert, relationship, commitment signals, motivation, or revision." },
      applications: { desert: "Dev deserves personal esteem only if bare later membership transfers the campaigners’ moral merit to him.", harm: "The pride highlights a real historical benefit but does not accurately identify Dev as its cause or contributor.", relationship: "Membership can connect Dev to a tradition, yet the shallow new relation supplies little basis for personal earned pride.", protest: "Pride might affirm equality against opposition, but the case removes any live opposing practice that needs resistance.", repair: "If pride motivates future contribution it may gain a forward role, but no such action is present in the fixed case.", expression: "Group pride can signal Dev’s present commitment to voting equality even while his personal desert claim overreaches.", regulation: "Dev can keep motivating identification if it supports action while reducing self-esteem that depends on borrowed achievement.", revise: "Replace deserved personal pride with admiration, gratitude for the campaigners, and responsibility for what he supports now." },
    },
    {
      id: "remorse", phase: "Accountability without moral facts", axis: "Case — the promise after error theory", prompt: "What, if anything, supports Omar’s remorse after he stops believing that promise-breaking is objectively wrong?",
      context: "Omar freely promised Lina that he would keep her medical history private. For convenience and social attention, he deliberately shared it, causing embarrassment and loss of trust but no material harm. He later becomes a moral error theorist: he no longer believes any act has approval-independent moral wrongness or that anyone intrinsically deserves suffering. He still cares about Lina, values reliable relationships, accepts that he violated his own commitment, and wants to repair the trust.",
      assumptions: "Omar’s metaethical change is sincere and informed, not an excuse. The promise, disclosure, embarrassment, and relationship damage are clear. Lina wants acknowledgment, prevention, and time—not Omar’s suffering.",
      scope: "Ask what supports remorse or a revised response after moral facts are rejected. Do not assume error theory erases harm, commitments, relationships, or practical reasons.", facts: ["Promise: voluntary", "Breach: deliberate", "Objective wrongness: rejected", "Repair: still possible"],
      why: "A deliberate betrayal after moral anti-realism tests whether accountability needs objective desert.", guide: { plain: "Can someone honestly regret and repair a betrayal while denying that it was objectively morally wrong?", separate: "Rejecting moral facts differs from rejecting the event, another person’s pain, or one’s own commitments.", reveal: "Your answer shows what remains of remorse, blame, and repair after desert is removed." },
      applications: { desert: "Omar’s remorse is fitting because the breach makes him objectively blameworthy and deserving despite his error theory.", harm: "The response recognizes Lina’s embarrassment, damaged trust, and Omar’s causal and intentional role without adding intrinsic desert.", relationship: "Remorse answers to the trust and expectation created by Omar’s voluntary promise to Lina.", protest: "Lina’s resentment or Omar’s acknowledgment can mark the privacy boundary and oppose treating the disclosure as normal.", repair: "Remorse is supported insofar as it motivates acknowledgment, protection, changed conduct, and patient rebuilding of trust.", expression: "Expressing remorse communicates that Omar still endorses privacy and reliable promises within shared practice.", regulation: "Omar can cultivate enough regret to remember and act while refusing self-punishment that serves neither Lina nor repair.", revise: "Replace deserved guilt with responsibility, regret, apology, prevention, and repair grounded in care and commitment." },
    },
  ],
  detectSeams: ({ answers, final, hits }) => {
    const seams = [];
    if (final?.family === "desert" && hits("desert") < 3) seams.push({ id: "functions-beyond-desert", title: "Most cases supported emotion through a role other than desert", detail: `Only ${hits("desert")} of seven cases used approval-independent desert, while the final account makes desert general. Clarify whether harm, relationship, protest, repair, expression, or regulation merely reveals desert or supplies a separate source.` });
    if (final?.family === "revise" && hits("revise") < 7) seams.push({ id: "retained-functions", title: "The final revision still leaves several emotions doing work", detail: `${7 - hits("revise")} case answer${7 - hits("revise") === 1 ? "" : "s"} retained a moral emotion for recognition, relationship, protest, repair, expression, or regulation. State which emotional form remains and which desert claim is removed.` });
    if (final?.family === "repair" && answers.resentment !== "revise" && answers.resentment !== "regulation") seams.push({ id: "after-repair", title: "Resentment remained after every repair task was complete", detail: "Your final account is forward-looking repair, but the repaired-betrayal case retained resentment through another role. Identify the remaining audience, boundary, relationship, or outcome that supports it." });
    if (final?.family === "expression" && answers.identity === "expression") seams.push({ id: "oppressive-signal", title: "The prejudice case exposes a limit on expressive usefulness", detail: "Village shame coordinated conduct successfully but enforced a harmless prejudice. A final expressive account needs a standard for deciding which commitments may be taught through shame or praise." });
    if (final?.family === "harm" && answers.pride !== "revise") seams.push({ id: "pride-without-causation", title: "Inherited pride reached beyond accurate causal appraisal", detail: "Dev did not cause the historical benefit. If his pride remains under a harm-and-benefit account, clarify whether it is really admiration, group identification, commitment signaling, or a claim to personal esteem." });
    return seams;
  },
  aiPremise: "Suppose approval-independent moral facts and intrinsic moral desert are not assumed. Ask what roles guilt, shame, resentment, indignation, gratitude, and pride can still play—and when their moralized form should be revised or retired.",
  aiCautions: [
    "Keep the cause of an emotion separate from the accuracy of its appraisal, the justification for expressing it, its intensity, and its duration.",
    "Keep causal responsibility, capacity to respond, relational accountability, and intrinsic moral desert distinct.",
    "Do not treat usefulness as sufficient when an emotion coordinates prejudice, manipulation, scapegoating, or coercive conformity.",
    "Do not prescribe therapy or diagnose a mental-health condition; identify conceptual and practical roles only.",
    "Revision can preserve regret, concern, memory, protest, boundaries, repair, appreciation, and trust without deserved suffering.",
  ],
};
