"use strict";

window.CASE_LAB_CONFIG = {
  id: "evidence",
  title: "Why Follow the Evidence?",
  familyOrder: ["truth", "aim", "desire", "useful", "inquiry", "social", "none"],
  skepticFamily: "none",
  defaultResultTitle: "Your answers gave evidence more than one possible source of force.",
  skepticTitle: "You ended by treating epistemic ‘oughts’ as useful shorthand.",
  leadingTitle: (familyId) => `${window.CASE_LAB_CONFIG.families[familyId].name} carried most of your cases.`,
  families: {
    truth: { index: "01", name: "Truth-directed evidence", short: "Evidence counts because it bears on whether a belief is true.", theory: "Stance-independent epistemic reason", note: "The evidential relation itself supplies support, even when truth is unwanted or useless. The account must explain why truth has normative force rather than merely describing what the evidence indicates." },
    aim: { index: "02", name: "The aim of belief", short: "Belief has a truth-directed job, and evidence shows whether it performs that job.", theory: "Constitutive or functional account", note: "Truth is treated as the correctness condition built into belief as a kind of state. The account must show why a constitutive standard becomes a reason for a person rather than merely a measure of proper function." },
    desire: { index: "03", name: "Truth-seeking aims", short: "Evidence matters through a person’s desire or project of getting the answer right.", theory: "Desire-dependent epistemic reason", note: "A reason to follow evidence depends on an actual or reflectively supported concern for truth, accuracy, consistency, or successful inquiry. The view must address agents who genuinely do not care." },
    useful: { index: "04", name: "Practical usefulness", short: "Evidence matters when accurate belief helps achieve a practical goal.", theory: "Epistemic instrumentalism", note: "Accurate belief receives force from safety, prediction, coordination, or another practical benefit. The account must explain useless truths and cases where a helpful false belief conflicts with the evidence." },
    inquiry: { index: "05", name: "Rules of inquiry", short: "Accepted standards for investigation give evidential discipline its force.", theory: "Practice- or commitment-based account", note: "The reason comes from participating in a practice with rules such as checking sources, correcting error, and responding to counterevidence. The authority and exit conditions of that practice remain open." },
    social: { index: "06", name: "Defensible social procedure", short: "Public methods for checking claims give evidence a shared form of authority.", theory: "Procedural or social-epistemic account", note: "Replication, open criticism, representation, and accountable institutions can support public belief. A fair procedure can still be mistaken, so the relation between procedural legitimacy and truth needs explanation." },
    none: { index: "07", name: "No literal epistemic ought", short: "Evidence predicts truth or changes belief, but nothing literally favors believing.", theory: "Epistemic anti-normativism", note: "Epistemic language is treated as description, recommendation, or useful practice rather than a genuine normative relation. The view must explain error, justification, and criticism without quietly restoring an ought." },
  },
  familyChoices: [
    { family: "truth", label: "The evidence itself counts in favor because it bears on whether the belief is true", detail: "A fact can support a belief even when nobody wants the truth, receives a benefit, or belongs to an inquiry practice.", establishes: "Evidence can provide a reason for belief independently of an agent’s aims or social acceptance.", limit: "The account still owes an explanation of why truth-indication has normative force and whether that force is genuinely objective." },
    { family: "aim", label: "Evidence counts in favor because a belief, by its nature, is supposed to represent the world accurately", detail: "Truth is the standard of correctness for belief, much as successful pumping is a standard for a heart functioning as a heart.", establishes: "A standard internal to belief may distinguish correct from incorrect believing without relying on a separate desire.", limit: "A constitutive standard does not automatically show that a person has a normative reason to satisfy it in every case." },
    { family: "desire", label: "Evidence counts in favor only through a person’s concern for truth, accuracy, or successful inquiry", detail: "The reason must connect to an actual desire or to a truth-seeking project the person would endorse after careful reflection.", establishes: "An agent’s practical outlook can make evidential accuracy matter without a stance-independent epistemic requirement.", limit: "The account may give no epistemic reason to a fully informed person who genuinely lacks every truth-seeking concern." },
    { family: "useful", label: "Evidence counts in favor when accurate belief helps protect something or achieve a practical goal", detail: "Prediction, safety, successful action, and coordination give people reasons to use methods that tend to produce true beliefs.", establishes: "Many ordinary reasons to follow evidence can be grounded in the practical effects of reliable belief.", limit: "The account must address useless truths and situations in which a comforting or beneficial false belief works better." },
    { family: "inquiry", label: "Evidence counts in favor because honest inquiry has rules that participants commit themselves to follow", detail: "Checking sources, exposing claims to criticism, and changing belief after counterevidence are constitutive standards of the chosen practice.", establishes: "A voluntary or socially sustained practice can supply internal standards for responsible investigation.", limit: "The account must explain the practice’s authority over outsiders and whether leaving it removes every epistemic reason." },
    { family: "social", label: "Evidence counts in favor through a fair and publicly defensible procedure for deciding what to accept", detail: "Open methods, independent checks, qualified participation, and correction procedures give a claim public standing.", establishes: "A transparent procedure can provide shared justification without relying on one person’s private certainty.", limit: "Public legitimacy and truth can separate; a fair community may still accept a false conclusion or exclude relevant evidence." },
    { family: "none", label: "Nothing literally counts in favor of belief; evidence only indicates, causes, or helps us manage beliefs", detail: "Calling evidence a reason is useful shorthand for truth-prediction, persuasion, inquiry rules, or practical success without an additional normative fact.", establishes: "Belief and inquiry can be described using causes, methods, and outcomes while rejecting literal epistemic reasons.", limit: "The view must explain what makes one belief mistaken, unjustified, or irrational without smuggling normative favoring back in." },
  ],
  opening: {
    axis: "Your starting account", prompt: "Before the cases, what can make evidence count in favor of believing something?",
    context: "Use ‘counts in favor’ to mean genuine support for a belief—not merely a cause of belief or a clue about what someone will think.",
    assumptions: "For this exercise, objective moral facts are set aside. No assumption has yet been made about truth, evidence, epistemic reasons, or standards of belief.",
    scope: "Choose the closest general account. The cases may reveal exceptions or show that you need more than one source.", why: "This records a starting definition without adding it to the seven-case bars.",
    guide: { plain: "Why, if at all, should a person let evidence change a belief?", separate: "Evidence can reliably indicate truth without yet explaining why truth or reliable indication gives anyone a reason.", reveal: "Your answer states the source of epistemic force you currently find most plausible." },
  },
  final: {
    axis: "Your final account", prompt: "After the cases, what can make evidence count in favor of believing something?",
    context: "Return to the same general question. Use ‘evidence’ for a consideration that bears on whether a claim is true.",
    assumptions: "The cases did not establish moral realism, epistemic realism, instrumentalism, or anti-normativism. Each remains an open account.",
    scope: "Choose the closest general account now. A change from the opening answer is reported as revision, not automatically as inconsistency.", why: "The repeated definition shows what the cases changed or clarified.",
    guide: { plain: "What now seems able to give evidence real weight in deciding what to believe?", separate: "A method can be reliable, useful, socially approved, and truth-directed in different combinations.", reveal: "The result compares this account with your opening answer and the exact sources used in each case." },
  },
  cases: [
    {
      id: "comfort", phase: "Truth against comfort", axis: "Case — the merciful scan", prompt: "What, if anything, gives the scan results a reason-giving force for Nia’s belief?",
      context: "A flawless deep-space scan proves that Nia’s missing partner died instantly. Believing that he is still alive would greatly reduce her grief for six months and would not change any decision, search effort, inheritance, or other person’s welfare. Nia understands the scan but strongly prefers the comforting belief.",
      assumptions: "The scan is conclusive. The true belief supplies no practical benefit during the six months. The false belief causes no practical harm and later fades without trauma.",
      scope: "Ask what supports belief now, not which emotional coping strategy is kindest or whether Nia should be forced to read the report.", facts: ["Evidence: conclusive", "True belief: painful", "False belief: helpful", "Practical decisions: unchanged"],
      why: "A harmless, helpful false belief separates truth-directed support from comfort and practical success.",
      guide: { plain: "Does evidence matter when accepting it only makes life worse and helps no decision?", separate: "A belief’s emotional benefit differs from evidence that the belief is true.", reveal: "Your answer shows whether evidential force survives when truth has no practical payoff." },
      applications: {
        truth: "The scan supports believing that he died even though the truth is unwanted and useless.", aim: "A belief that he survived would fail belief’s truth-representing function.", desire: "Nia has a reason only if some concern for accuracy survives her wish for comfort.", useful: "The evidence supplies no practical reason here; the helpful false belief may be preferable for the stated goal.", inquiry: "If Nia continues the inquiry, its correction rules require accepting the conclusive scan.", social: "A defensible public process would record the scan’s conclusion even if Nia privately copes differently.", none: "The scan indicates death and the false belief comforts; no further epistemic ought selects between them.",
      },
    },
    {
      id: "trivial", phase: "Truth without a use", axis: "Case — the 17,429th digit", prompt: "Does unused evidence give anyone a reason to believe this completely trivial fact?",
      context: "A verified calculation establishes the 17,429th digit of a newly defined mathematical constant. No theorem, machine, prediction, archive, contest, or person’s project will ever depend on that digit. Rui sees the proof, understands it fully, and feels no curiosity about the answer.",
      assumptions: "The proof is sound and easy to understand. Remembering the digit has no cost, benefit, symbolic meaning, or future use. Nobody else cares.",
      scope: "Ask whether the proof counts in favor of belief, not whether Rui has a practical reason to spend time studying other mathematics.", facts: ["Proof: sound", "Use: none", "Curiosity: none", "Memory cost: none"],
      why: "A useless truth tests whether epistemic reasons need practical value or personal interest.",
      guide: { plain: "Can evidence support a belief when the truth matters to nobody and changes nothing?", separate: "The question is not whether learning the fact was worth the effort; the proof is already understood.", reveal: "Your answer shows whether evidential support depends on usefulness or desire." },
      applications: { truth: "The proof supports the digit simply because it makes the claim true.", aim: "Any belief about the digit is correct only if it matches the proven answer.", desire: "Rui lacks a truth-seeking concern here, so no personal epistemic reason is generated.", useful: "With no practical function, the proof gives Rui no reason to form or retain the belief.", inquiry: "Understanding the proof while participating in mathematics activates the practice’s acceptance rule.", social: "The verified procedure warrants public acceptance even though the result is trivial.", none: "The proof entails the digit, but there is no additional fact that Rui should believe it." },
    },
    {
      id: "forecast", phase: "Evidence against agreement", axis: "Case — the unanimous weather room", prompt: "What should give the instrument reading authority over the room’s preferred forecast?",
      context: "Twelve experienced forecasters unanimously prefer a calm-weather prediction because an evacuation would be exhausting and politically damaging. A newly calibrated instrument, independently checked by three laboratories, shows a lethal pressure wave arriving tomorrow. Everyone understands that the instrument has a far better record than unaided judgment.",
      assumptions: "The calibration and track record are genuine. The instrument could still be wrong, but its probability estimate is much better. The vote was informed and uncoerced.",
      scope: "Ask what counts in favor of the storm belief, not whether officials should order evacuation or how large the danger must be.", facts: ["Vote: 12–0 for calm", "Instrument: independently checked", "Accuracy: much higher", "Political cost: severe"],
      why: "Unanimous preference and procedural agreement can conflict with truth-tracking evidence.",
      guide: { plain: "Why believe the better instrument when every informed person wants the other forecast?", separate: "A fair vote can decide policy without making the winning factual prediction more likely to be true.", reveal: "Your answer locates authority when evidence and agreement separate." },
      applications: { truth: "The instrument’s likelihood relation supports the storm belief despite unanimous opposition.", aim: "A forecast functions as a representation of coming weather, so accuracy governs it.", desire: "The forecasters’ deeper concern for successful prediction can outweigh their current political preference.", useful: "Accurate belief serves survival and planning, giving the instrument strong practical force.", inquiry: "Calibration, replication, and updating are rules the forecasters accepted as investigators.", social: "Independent laboratories and transparent checks make the instrument the publicly defensible basis.", none: "The reading predicts a storm and the vote predicts calm; calling one normatively required adds no further fact." },
    },
    {
      id: "lucky", phase: "Truth without justification", axis: "Case — the lucky conspiracy", prompt: "Does accidentally reaching the truth make the conspiracy method a reason to believe?",
      context: "Milo believes a meteor will strike because a celebrity’s shoe color matches a pattern in old song titles. By coincidence, a meteor really will strike. At the time of belief, ordinary telescopes showed no meteor because it was hidden behind the sun; later measurements reveal it.",
      assumptions: "The shoe-and-song method has no reliable connection to meteors. Milo’s conclusion is true by luck. He sincerely followed his method and belongs to a group that approves it.",
      scope: "Ask what supported the belief when Milo formed it. Do not use later evidence that he did not possess.", facts: ["Conclusion: true", "Method: unreliable", "Group approval: strong", "Later evidence: unavailable then"],
      why: "Lucky truth separates a belief’s truth from the quality of the route used to reach it.",
      guide: { plain: "Is being right enough, or must the evidence connect reliably to the truth?", separate: "A true conclusion can be badly supported; a reasonable belief can also turn out false.", reveal: "Your answer shows whether epistemic appraisal targets results, methods, agents, or practices." },
      applications: { truth: "The shoe pattern did not bear on the truth, so it supplied no truth-directed support despite the lucky result.", aim: "The belief happened to function accurately, but the process did not reliably perform belief’s representational job.", desire: "Milo’s wish to be right motivates him but cannot turn an unrelated pattern into support.", useful: "If the belief prompts effective preparation, it may have practical value despite its defective basis.", inquiry: "The method violates ordinary checking and error-correction rules, so it lacks practice-based warrant.", social: "Approval inside an insulated group is not a defensible procedure without relevant checks and criticism.", none: "The method caused a true belief by luck; that complete description requires no normative verdict of justification." },
    },
    {
      id: "archive", phase: "Support without access", axis: "Case — the sealed archive", prompt: "Can forgotten evidence still count in favor when only the conclusion remains?",
      context: "Dr. Sen carefully reviewed a secure archive and formed the true belief that a reactor component was defective. A required privacy treatment then erased every memory of the documents and reasoning while leaving the conclusion intact. She knows that her archive reviews are normally meticulous but cannot reopen this one.",
      assumptions: "Her original evidence was decisive and her reasoning was excellent. She now remembers only the conclusion and her general reliability. Acting on the belief would delay launch at moderate cost.",
      scope: "Ask what currently supports the belief, distinguishing the lost first-order evidence from present evidence about her own reliability.", facts: ["Original evidence: decisive", "Memory: erased", "Conclusion: retained", "General reliability: known"],
      why: "Lost evidence tests whether support belongs to a person’s present perspective, the truth relation, or a reliable process.",
      guide: { plain: "Do reasons for belief disappear when you can no longer remember the evidence?", separate: "The old documents and present trust in one’s past method are different evidence.", reveal: "Your answer shows whether epistemic support must be accessible now." },
      applications: { truth: "The original documents still bear on the component’s condition, while her known reliability supplies new indirect evidence.", aim: "Retaining a belief without accessible support may imperfectly perform belief’s truth-directed function, despite the reliable origin.", desire: "Her concern for accurate safety decisions gives her reason to rely cautiously on her remembered conclusion.", useful: "The expected safety benefit of respecting a normally meticulous review can justify delay.", inquiry: "The practice should specify how inaccessible evidence and audit trails are handled; its rule supplies the answer.", social: "Independent review or a public safety protocol is needed before the inaccessible conclusion governs others.", none: "The past process caused a true retained belief and present reliability predicts success; no further favoring relation is required." },
    },
    {
      id: "placebo", phase: "Useful false belief", axis: "Case — the honest placebo", prompt: "What should happen when evidence favors truth but practical success requires false belief?",
      context: "A harmless capsule reliably stops Arlo’s severe pain only while he believes it contains a powerful medicine. Conclusive laboratory evidence shows that it is inert. Arlo has read the report but can choose to cultivate the false medicine belief through immersive suggestion, restoring the pain relief.",
      assumptions: "The false belief produces large relief and no medical side effect. The true belief leaves the pain. No one is deceived, and Arlo understands the choice before entering suggestion.",
      scope: "Ask what counts in favor of the belief itself. Keep that separate from whether Arlo has a practical reason to undergo suggestion.", facts: ["Evidence: capsule inert", "False belief: relieves pain", "True belief: pain remains", "Consent: informed"],
      why: "A beneficial false belief puts epistemic support and practical reason in direct conflict.",
      guide: { plain: "Can a false belief be the better belief when it safely stops serious pain?", separate: "Evidence may support one belief while practical goals support causing another.", reveal: "Your answer shows whether epistemic and practical reasons can point in opposite directions." },
      applications: { truth: "The evidence supports believing the capsule inert even if Arlo has a separate practical reason to induce false belief.", aim: "The false medicine belief fails belief’s accuracy standard while perhaps serving another psychological function.", desire: "Arlo’s competing aims—accuracy and pain relief—determine which reason his outlook supplies.", useful: "Pain relief gives the false belief a strong practical basis, while truth has no useful advantage here.", inquiry: "Medical inquiry should record the inert result even if a therapeutic practice permits induced belief under consent.", social: "A transparent procedure can distinguish the public medical record from Arlo’s private therapeutic choice.", none: "Evidence indicates inertness and suggestion causes relief; no literal epistemic or practical ought is needed to describe the conflict." },
    },
    {
      id: "indifferent", phase: "The person who does not care", axis: "Case — the indifferent logician", prompt: "Does evidence give Tavi a reason when Tavi has no concern for truth or consistency?",
      context: "Tavi holds two directly contradictory beliefs about a distant empty moon. Clear evidence resolves the contradiction. Tavi understands it but has no desire for truth, consistency, reputation, achievement, or successful action in this subject. No present or future choice will be affected.",
      assumptions: "Tavi is not confused, impaired, or hiding another goal. The contradiction has no practical consequence. Changing either belief is effortless.",
      scope: "Ask whether Tavi has an epistemic reason to revise, not whether observers dislike contradiction or can cause Tavi to change.", facts: ["Contradiction: understood", "Evidence: clear", "Truth concern: none", "Practical consequence: none"],
      why: "A fully indifferent believer tests whether epistemic reasons depend on an agent’s motivations.",
      guide: { plain: "Can evidence give someone a reason when they truly do not care about being right?", separate: "We may want Tavi to revise; the question is whether the evidence itself or some standard gives Tavi a reason.", reveal: "Your answer fixes the reach of epistemic reasons beyond personal aims." },
      applications: { truth: "The resolving evidence counts in favor for Tavi despite total indifference.", aim: "Contradictory belief fails the constitutive truth-representing standard whether Tavi cares or not.", desire: "With no truth-seeking or practical aim, Tavi has no epistemic reason to revise.", useful: "Because no action or welfare depends on the belief, practical usefulness supplies no reason.", inquiry: "Tavi has a reason only if participation in an inquiry practice remains a commitment; the case says none is active.", social: "A public record may need correction, but that procedural reason need not become Tavi’s personal reason.", none: "Evidence resolves the contradiction as a descriptive matter, but nothing literally favors Tavi’s revision." },
    },
  ],
  detectSeams: ({ answers, final, hits, selected }) => {
    const seams = [];
    if (final?.family === "none" && hits("none") < 7) seams.push({ id: "skeptic-cases", title: "The final skeptical account is narrower than several case answers", detail: `${7 - hits("none")} case answer${7 - hits("none") === 1 ? "" : "s"} treated truth, belief’s aim, an agent’s project, usefulness, inquiry rules, or procedure as genuine support while the final answer rejects literal epistemic reasons.` });
    if (final?.family === "useful" && selected("trivial", "truth")) seams.push({ id: "useless-truth", title: "A useless truth received support under a usefulness-only account", detail: "The trivial digit case treated truth-directed evidence as supporting belief even though the final account requires practical usefulness. Clarify whether truth itself sometimes supplies a reason." });
    if (final?.family === "desire" && !["desire", "none"].includes(answers.indifferent)) seams.push({ id: "unmoved-agent", title: "The indifferent believer received a reason beyond desire", detail: "Your final account requires a truth-seeking aim, but the fully indifferent Tavi case used a source that did not depend on Tavi wanting accuracy. State whether that case is an exception." });
    return seams;
  },
  aiPremise: "Suppose there are no objective moral facts. Ask separately whether evidence can still give normative reasons for belief. Do not assume that moral anti-realism entails epistemic realism, epistemic anti-realism, or the reverse.",
  aiCautions: [
    "Keep truth, evidence, usefulness, belief’s function, personal motivation, inquiry rules, and social procedure distinct.",
    "A true belief can be badly supported, and a well-supported belief can turn out false.",
    "A practical reason to cause a belief is not automatically evidence that the belief is true.",
    "Do not treat the companions-in-guilt challenge as an automatic refutation of moral non-realism.",
  ],
};
