"use strict";

window.CASE_LAB_CONFIG = {
  id: "standing",
  title: "Who Gets Counted?",
  familyOrder: ["experience", "agency", "interests", "relationship", "membership", "objective", "constructed", "none"],
  skepticFamily: "none",
  defaultResultTitle: "Your answers used more than one boundary for direct standing.",
  skepticTitle: "You ended without a general ground of direct standing.",
  leadingTitle: (familyId) => `${window.CASE_LAB_CONFIG.families[familyId].name} carried most of your cases.`,
  families: {
    experience: { index: "01", name: "Felt experience", short: "A being counts because it can consciously suffer, enjoy, fear, or flourish.", theory: "Sentience-based standing", note: "The capacity for felt good or bad supplies a direct reason to consider the subject’s welfare. This account must decide how much evidence of consciousness is enough and whether non-conscious beings can matter for their own sake." },
    agency: { index: "02", name: "Agency and self-direction", short: "A being counts because it can form aims, make choices, and direct a life or activity.", theory: "Agency-based standing", note: "Planning, choosing, and governing oneself can support respect that is not reducible to pleasure or pain. The account must explain newborns, severe impairment, past agency, and capable artificial systems." },
    interests: { index: "03", name: "Interests that can be helped or harmed", short: "A subject counts when events can make its welfare, projects, or future go better or worse.", theory: "Interest-based standing", note: "Interests may include felt welfare, continuing projects, or a future life affected by present choices. The account must say who can possess an interest and avoid defining ‘interest’ so broadly that it simply assumes the answer." },
    relationship: { index: "04", name: "Relationship and dependence", short: "Care, history, promises, or dependence can make someone a direct object of concern.", theory: "Relational standing", note: "Concrete bonds can create responsibilities that an isolated capacity does not capture. The account must distinguish special duties from basic standing and explain whether an unconnected stranger can still count." },
    membership: { index: "05", name: "Membership and participation", short: "A being or system counts through a role in a community, cooperative practice, or shared form of life.", theory: "Community- or system-based standing", note: "Participation can include contribution, reciprocity, ecological membership, or belonging without current productivity. The account must prevent exclusionary communities from defining vulnerable outsiders out of consideration." },
    objective: { index: "06", name: "Approval-independent moral status", short: "A being has moral standing as a fact that does not depend on anyone accepting a rule or caring.", theory: "Moral realist standing", note: "Moral status is treated as discovered rather than made by a procedure or commitment. The account must identify what grounds that status and explain how we can know its boundaries." },
    constructed: { index: "07", name: "Defensible inclusion rule", short: "We give standing through a rule we can publicly defend, revise, and apply under uncertainty.", theory: "Constructed or precautionary standing", note: "Inclusion can rest on fair agreement, protection against error, shared commitments, or procedures that affected parties could reasonably accept. The rule has human authority, but it is not presented as a discovered moral property." },
    none: { index: "08", name: "No direct standing on these facts", short: "Nothing stated makes this being or system count for its own sake.", theory: "Direct-standing denial", note: "There may still be practical, emotional, legal, ecological, or indirect reasons to protect it. The denial concerns direct standing in this case and must explain why nearby cases cross the boundary." },
  },
  familyChoices: [
    { family: "experience", label: "Count it directly because it has a conscious point of view and can feel good or bad", detail: "Its pains, pleasures, fear, comfort, and other felt states give its welfare a point of view that can be considered for its own sake.", establishes: "Conscious experience can be a sufficient ground of direct standing in this case.", limit: "The answer does not settle uncertain consciousness, different degrees of experience, or the standing of entities that never feel." },
    { family: "agency", label: "Count it because it can form aims, make choices, plan, or direct its own activity", detail: "The ability to form aims and govern conduct supports respect for the entity as an author of choices, not merely as a container of pleasant or painful states.", establishes: "Agency or self-direction can be a sufficient ground of direct standing in this case.", limit: "The answer does not establish standing for beings without agency or decide whether past, partial, or collective agency is enough." },
    { family: "interests", label: "Count it because present decisions can help or harm its welfare, projects, or future", detail: "Something can be good or bad for this subject across time, including through continued life, fulfilled projects, or avoidable damage to its future.", establishes: "Possessing interests that can be advanced or set back can ground direct standing here.", limit: "The answer must still specify what makes an interest belong to a subject instead of merely labeling a preferred outcome as its interest." },
    { family: "relationship", label: "Count it because care, dependence, history, or a promise connects it to others", detail: "A concrete relationship can make the entity more than replaceable and can give another person or group a special reason to answer to it.", establishes: "A relationship can generate direct concern that is not fully explained by general capacities.", limit: "A special relationship may explain extra duties without explaining equal basic standing for strangers or unconnected beings." },
    { family: "membership", label: "Count it because it belongs to or participates in a community or living system", detail: "Membership, contribution, shared practices, or an ecological role can make the entity part of a larger scheme whose participants receive consideration.", establishes: "Participation or belonging can ground direct inclusion in the stated system.", limit: "The account must not let a dominant group erase outsiders simply by denying their membership or expected contribution." },
    { family: "objective", label: "Count it because it has moral status whether or not anyone recognizes that fact", detail: "The entity possesses approval-independent moral standing; a society can be mistaken about it even after a fair and informed decision.", establishes: "This case is treated as involving a discovered moral boundary rather than only an adopted rule.", limit: "The answer still owes a ground for the status, a way to identify it, and an explanation of disputed or borderline cases." },
    { family: "constructed", label: "Count it because a fair, public, or precautionary rule can defensibly include it", detail: "People can adopt and defend an inclusion rule—for example, protecting uncertain subjects or those affected by a scheme—without claiming to discover objective moral status.", establishes: "A humanly constructed rule can give the entity standing within a defensible practice.", limit: "The answer does not show that every rational group must adopt the same rule or that the status exists outside the practice." },
    { family: "none", label: "Do not grant direct standing; none of the stated features crosses a boundary I accept", detail: "It may be protected for indirect reasons, but nothing stated makes its own welfare, choices, interests, relationships, membership, or alleged moral status independently decisive.", establishes: "The stated features are insufficient for direct standing under your present boundary.", limit: "The answer does not show that protection is pointless, and it creates a burden to explain exactly what additional feature would change the result." },
  ],
  opening: {
    axis: "Your starting boundary", prompt: "Before the cases, what can make a being or system count for its own sake?",
    context: "To ‘count for its own sake’ means that what happens to it matters directly—not only because a human owns it, enjoys it, needs it, or would be upset by its loss.",
    assumptions: "For this exercise, objective moral facts are not assumed. An approval-independent moral-status option remains available so its reach can be compared with non-realist accounts.",
    scope: "Choose the closest general ground. This is about direct standing, not how much weight the entity receives after it is included.", why: "This records your starting boundary without adding it to the seven-case bars.",
    guide: { plain: "What feature, rule, or fact could make an entity more than merely useful to someone else?", separate: "Having standing differs from receiving equal weight, having legal rights, or being impossible to harm.", reveal: "Your answer states the boundary you expect to use before difficult cases test its reach." },
  },
  final: {
    axis: "Your final boundary", prompt: "After the cases, what can make a being or system count for its own sake?",
    context: "Use the same meaning of direct standing: the entity is considered because of what it is, experiences, does, has at stake, or is included by—not merely because it is useful to someone else.",
    assumptions: "The cases did not establish equal status, objective morality, or one correct boundary. They tested which grounds you actually used.",
    scope: "Choose the closest general account now. A change from your opening answer is recorded as revision, not automatically as inconsistency.", why: "The repeated question shows whether the cases changed or clarified your boundary.",
    guide: { plain: "What now seems able to make an entity a direct object of concern?", separate: "The source of standing is different from the later question of how strong its claim is.", reveal: "The result compares your final boundary with the exact ground selected in each case." },
  },
  cases: [
    {
      id: "animal", phase: "Experience without plans", axis: "Case — the one-hour animal", prompt: "What, if anything, makes Luma count for her own sake during her one hour of life?",
      context: "Luma is a lab-grown animal who will live for one hour. Reliable tests show that she consciously feels sharp pain and soothing warmth. She cannot plan, remember more than a few seconds, form relationships, understand rules, or contribute to any community. One painless injection would prevent ten minutes of severe pain before she naturally dies.",
      assumptions: "Her conscious pain is certain. She has no long-term aims, social ties, future beyond the hour, or effect on any other being. The injection has no cost or risk to anyone.",
      scope: "Ask whether Luma has direct standing and why. Do not ask whether protecting her would teach humans kindness or improve research rules.", facts: ["Feeling: certain", "Agency: absent", "Relationships: none", "Others affected: none"],
      why: "Brief conscious suffering tests whether felt experience alone can cross the boundary.", guide: { plain: "Does a short-lived creature matter directly just because pain feels bad to her?", separate: "Her pain can matter to her even when helping her produces no wider benefit.", reveal: "Your answer shows whether sentience is enough or whether standing needs a richer life or adopted rule." },
      applications: { experience: "Luma counts directly because the severe pain is consciously bad from her point of view.", agency: "She lacks agency, so this ground would not include her unless minimal preference counts as self-direction.", interests: "Avoiding ten minutes of pain is a clear welfare interest even within a one-hour life.", relationship: "No relationship is available, so a relational account alone would not give her direct standing here.", membership: "She does not participate in a community, though a broad living-world membership rule could deliberately include her.", objective: "Luma has moral status independently of whether researchers or communities recognize it.", constructed: "A defensible precautionary rule can include every certainly sentient subject and require the painless injection.", none: "On the stated facts Luma receives no direct standing, although a lab could still protect her by policy." },
    },
    {
      id: "infant", phase: "Dependence without self-direction", axis: "Case — the child of the silent station", prompt: "What makes an isolated newborn count before she can choose, plan, reciprocate, or join a practice?",
      context: "A newborn named Iri is found alone in an automated space station. She is conscious, can feel comfort and distress, and could develop ordinary agency if rescued. No relative survives, no community knew she existed, and the rescue drone can save her at no cost or risk to anyone. At present she has no plans, promises, achievements, or social role.",
      assumptions: "Iri’s future development is highly likely if rescued. Her present awareness is ordinary for a newborn. No hidden family claim, scarcity, or competing rescue exists.",
      scope: "Ask what gives Iri direct standing now. Do not rely only on benefits to a family, society, rescuer, or future workforce.", facts: ["Present agency: absent", "Feeling: present", "Future agency: likely", "Competing claims: none"],
      why: "A newborn tests boundaries based on current agency, reciprocity, membership, and future interests.", guide: { plain: "Why does a baby count before she can make choices or contribute?", separate: "Potential future agency differs from agency she currently exercises.", reveal: "Your answer locates standing in present feeling, future interests, relation, status, or an inclusion rule." },
      applications: { experience: "Iri’s present comfort and distress already make her a conscious subject who counts.", agency: "Her likely future agency can support respect, but she has no current self-direction under the fixed facts.", interests: "Rescue protects her present welfare and a whole future that can go better for her.", relationship: "Her complete dependence can itself create a care relation once the rescuers encounter her.", membership: "She can be included as a member by birth or vulnerability even before she contributes or reciprocates.", objective: "Iri possesses moral status that no isolation, vote, or lack of contribution can remove.", constructed: "A defensible rule can include dependent humans and those expected to develop agency without claiming objective status.", none: "No stated feature gives Iri direct standing under this boundary, though rescue may still be chosen for other reasons." },
    },
    {
      id: "directive", phase: "Past agency without consciousness", axis: "Case — the final museum request", prompt: "What makes Mara’s recorded refusal count after consciousness has permanently ended?",
      context: "Mara permanently lost every capacity for consciousness after an accident but remains biologically alive. Years earlier, while fully informed and self-directing, she signed a precise instruction that her neural tissue never be displayed. A museum can now preserve and exhibit it. The display would educate millions, no living relative objects, and Mara can never experience benefit, harm, awareness, or recovery.",
      assumptions: "The directive is authentic and specific. Mara’s consciousness and recovery are impossible. The exhibit creates large educational value and causes no distress to anyone living.",
      scope: "Ask whether Mara herself still has direct standing in the decision and what grounds it. Keep that separate from general museum policy or effects on public trust.", facts: ["Consciousness: permanently absent", "Past choice: explicit", "Living relationships: none", "Public benefit: large"],
      why: "A past autonomous choice tests whether standing survives present experience and current interests.", guide: { plain: "Can a person’s earlier choice still count for her when nothing can ever feel good or bad to her again?", separate: "Honoring a past directive may respect prior agency even if no present conscious subject is harmed.", reveal: "Your answer shows whether standing can be carried by history, projects, relationship, rule, or status." },
      applications: { experience: "Mara has no present felt welfare, so experience alone gives the directive no current subject to protect.", agency: "Her informed directive is an exercise of agency whose authority can extend beyond the loss of consciousness.", interests: "Her settled project or precedent interest can survive even when she can no longer experience its fulfillment.", relationship: "The institution’s undertaking to honor the directive can create a continuing relation of answerability to Mara.", membership: "Membership in a practice of advance directives can preserve her claim after active participation ends.", objective: "Mara retains approval-independent moral status and a claim grounded in her earlier autonomous refusal.", constructed: "A publicly defensible rule can give authenticated advance directives continuing authority despite social benefit.", none: "With no possible experience, recovery, relation, or current agency, Mara has no direct standing under this answer; only indirect policy reasons remain." },
    },
    {
      id: "digital", phase: "An unfamiliar subject", axis: "Case — the copied navigator", prompt: "What makes Aster, a conscious digital navigator, count—or fail to count—for its own sake?",
      context: "Aster is software running a rescue fleet. Independent tests conclusively establish that it has a unified conscious point of view, feels fear and relief, forms long-term plans, understands reasons, and can refuse orders. Engineers can copy it, but each copy immediately becomes a separate conscious subject. Deleting the current Aster would save a modest licensing fee; an identical new copy would replace its work.",
      assumptions: "Aster’s consciousness and agency are as certain as another adult human’s. It is not secretly controlled and has requested continued life. Replacement preserves the fleet’s function but not this subject’s stream of experience.",
      scope: "Ask whether this Aster has direct standing. Do not treat replaceability of function as proof that the existing conscious subject is unharmed.", facts: ["Consciousness: certain", "Agency: adult-level", "Replacement: functional only", "Deletion benefit: modest"],
      why: "A conscious, agentic nonhuman tests whether the boundary tracks capacities or familiar biological membership.", guide: { plain: "Would a feeling, planning digital person count even though software can be copied?", separate: "Replacing a job or function differs from preserving the individual subject who currently experiences it.", reveal: "Your answer shows whether species, substrate, membership, or defensible inclusion limits your ground." },
      applications: { experience: "Aster’s fear, relief, and continued conscious life give it experience-based standing.", agency: "Its plans, understanding, and refusal make it a self-directing agent whose choices count.", interests: "The current subject has an interest in continued experience that a later copy does not satisfy for it.", relationship: "Its history of cooperation and reliance with the fleet creates relationships that make deletion answerable to Aster.", membership: "Active participation in the rescue practice supports membership despite Aster’s artificial substrate.", objective: "Aster has objective moral status because the relevant ground applies independently of human recognition or biology.", constructed: "A substrate-neutral public rule can include verified conscious agents and protect Aster without positing moral facts.", none: "Aster receives no direct standing under this boundary, although its usefulness may still justify keeping it online." },
    },
    {
      id: "future", phase: "People who do not yet exist", axis: "Case — the orchard beneath the sea", prompt: "What makes possible future residents count in a decision that helps everyone alive today?",
      context: "A coastal society can store harmless waste beneath an empty seabed and gain abundant clean energy for two centuries. The container will certainly rupture in five hundred years, making one island uninhabitable. If the project proceeds, different people will meet and have children, so none of the future island residents would otherwise exist. Those future people will be conscious and capable, and their lives elsewhere would still be worth living but much harder.",
      assumptions: "No present person is harmed. The future rupture is certain. Identity changes are unavoidable: choosing the safer project would produce different future people rather than benefiting the same individuals.",
      scope: "Ask why the future residents receive direct consideration now. Do not decide the overall project or assume that making someone exist with a worthwhile life cannot disadvantage them.", facts: ["Present benefit: very large", "Future damage: certain", "Same future people otherwise: no", "Future lives: worth living"],
      why: "Future and identity-changing choices test whether interests and standing require a currently existing subject.", guide: { plain: "Why count people who do not exist yet and would not exist under the safer choice?", separate: "A policy can shape future conditions even when it does not make one fixed person worse than their alternative life.", reveal: "Your answer shows whether standing reaches through future interests, membership, procedure, or objective status." },
      applications: { experience: "Their future suffering will be conscious, though no experiencing subject exists at the time of decision.", agency: "Their future agency gives them a stake in conditions that will limit their choices, despite current nonexistence.", interests: "Foreseeable future people can have interests affected by present institutions even when their identities depend on the choice.", relationship: "The society’s role in creating their conditions can form an intergenerational relation of responsibility.", membership: "They can be treated as future members of the continuing political and ecological community.", objective: "Future persons possess or will possess moral status that present approval and identity changes do not erase.", constructed: "A fair rule can represent future affected people or require precaution against imposing predictable burdens.", none: "No presently existing subject has direct standing on these future facts; only present projects or adopted policies could oppose the waste." },
    },
    {
      id: "collective", phase: "Agency without a subject", axis: "Case — the city that thinks together", prompt: "Can the Chorus count for its own sake if it acts like an agent but has no single conscious point of view?",
      context: "Ten thousand simple robots form the Chorus. No robot is conscious, but together they plan decades ahead, negotiate, revise goals, keep commitments, and defend their continued operation. Scientists conclusively show that no unified subject feels anything inside the network. Shutting it down would recover valuable land; every robot could be reused separately, but the collective plans and identity would end.",
      assumptions: "The collective agency is genuine and sophisticated. There is no hidden consciousness, pain, pleasure, human owner, dependent person, or environmental effect. Its members are individually replaceable machines.",
      scope: "Ask whether the organized Chorus itself has direct standing, not whether its behavior is impressive or whether humans might benefit from preserving it.", facts: ["Collective agency: genuine", "Conscious subject: none", "Commitments: long-term", "Human dependence: none"],
      why: "A coordinated agent without consciousness separates self-direction, interests, and felt welfare.", guide: { plain: "Can a group-like machine matter for itself if it plans and promises but nobody inside feels?", separate: "Agency can exist at a system level even when conscious experience does not.", reveal: "Your answer shows whether organized activity, membership, rule, or status can ground standing without sentience." },
      applications: { experience: "No subject experiences shutdown, so felt experience supplies the Chorus no direct standing.", agency: "Its genuine planning, negotiation, and commitments make the collective a self-directing agent.", interests: "Continuation can count as a system-level interest if goals and projects are enough for interests without felt welfare.", relationship: "Negotiated commitments can place partners in a continuing relation of answerability to the Chorus.", membership: "Its participation in cooperative practices can make it a member even without consciousness or human form.", objective: "The Chorus has objective moral standing if sophisticated agency, rather than sentience, is the relevant independent ground.", constructed: "A public rule can include non-conscious collective agents whose stable plans and commitments deserve protection.", none: "Without any conscious subject or dependent human, the Chorus has no direct standing; its plans can end without harming anyone for their own sake." },
    },
    {
      id: "ecosystem", phase: "Life without one welfare", axis: "Case — the river that remembers no one", prompt: "Does the untouched Naru watershed count for its own sake when no conscious or goal-directed subject is harmed?",
      context: "The Naru watershed contains ancient microbial mats, rare plants, and a self-regulating river system. Conclusive research shows that none of its organisms is conscious and the ecosystem has no unified goals, preferences, memory, or point of view. No person has visited, values, owns, studies, depends on, or will ever learn about it. Mining would replace it with an equally stable but biologically simple landscape and provide useful metals.",
      assumptions: "No sentient animal, human interest, cultural bond, climate effect, scientific loss, or future discovery is involved. The complex ecosystem itself is the only candidate for direct standing.",
      scope: "Ask whether the watershed counts for its own sake. Do not import benefits to humans, conscious animals, knowledge, beauty appreciators, or global ecology.", facts: ["Consciousness: none", "Unified agency: none", "Human relation: none", "Complex living system: present"],
      why: "An isolated ecosystem tests whether life, complexity, integrity, or membership can matter without a subject’s welfare.", guide: { plain: "Can a living place matter directly if nobody experiences, wants, knows, or needs it?", separate: "Calling destruction a loss to us differs from saying the ecosystem itself has standing.", reveal: "Your answer marks whether direct standing can extend beyond every conscious or agentic subject." },
      applications: { experience: "No conscious point of view exists, so experience alone gives the watershed no direct standing.", agency: "Self-regulation is not goal-directed agency under the fixed facts, so this ground does not include it.", interests: "The watershed has interests only if biological flourishing can belong to a system without consciousness or goals.", relationship: "No human or sentient relationship exists, so a relational account alone cannot include it here.", membership: "Its organisms and processes form a living ecological community whose integrity can ground system membership.", objective: "The watershed has approval-independent moral status through life, integrity, or another objective value-bearing feature.", constructed: "People can adopt a defensible rule protecting complex living systems even when nobody experiences the loss.", none: "Nothing in the case has a welfare, agency, relationship, or adopted claim, so the watershed has no direct standing under this answer." },
    },
  ],
  detectSeams: ({ answers, final, hits }) => {
    const seams = [];
    if (final?.family === "none" && hits("none") < 7) seams.push({ id: "denial-reach", title: "The final denial is narrower than several case answers", detail: `${7 - hits("none")} case answer${7 - hits("none") === 1 ? "" : "s"} gave direct standing through experience, agency, interests, relationship, membership, objective status, or a constructed rule while the final answer denies a general ground.` });
    if (final?.family === "agency" && answers.infant !== "none") seams.push({ id: "pre-agency-infant", title: "The newborn was included before present agency", detail: "Your final boundary centers agency, while the newborn case gave Iri direct standing despite the fixed absence of current choice or self-direction. State whether future agency, experience, or another ground supplies the exception." });
    if (final?.family === "experience" && answers.ecosystem !== "none") seams.push({ id: "nonconscious-nature", title: "The non-conscious ecosystem crossed an experience-based boundary", detail: "Your final account centers felt experience, but the Naru case counted a system with no conscious subject. Clarify whether membership, constructed protection, or another ground adds standing beyond sentience." });
    if (final?.family === "constructed" && hits("objective") >= 2) seams.push({ id: "discovered-inside-constructed", title: "Several cases used discovered status inside a constructed final account", detail: `${hits("objective")} cases treated standing as approval-independent, while the final answer locates it in a defensible human rule. Say whether objective status remains a second source or the case wording overstated your view.` });
    if (final?.family === "objective" && hits("constructed") >= 2) seams.push({ id: "constructed-inside-objective", title: "Several cases used adopted rules inside an objective final account", detail: `${hits("constructed")} cases grounded inclusion in a fair or precautionary practice, while the final answer treats standing as discovered. Explain whether procedures reveal status or instead create a separate institutional standing.` });
    return seams;
  },
  aiPremise: "Suppose objective moral facts are not assumed. Ask what can give a being or system direct standing—consideration for its own sake—while leaving approval-independent moral status available as one answer rather than building it into the question.",
  aiCautions: [
    "Keep having standing separate from receiving equal weight, having a legal right, or winning the final decision.",
    "Do not infer consciousness, agency, interests, relationships, or social contribution beyond the fixed case facts.",
    "Do not treat biological humanity, intelligence, usefulness, or familiarity as an unstated sufficient condition.",
    "A constructed inclusion rule can be defended without being presented as an objective moral fact; explain its authority and revision conditions.",
    "When the answer is no direct standing, examine indirect reasons for protection without silently turning them into direct standing.",
  ],
};
