"use strict";

window.CASE_LAB_CONFIG = {
  id: "tradeoffs",
  title: "When Values Won’t Add Up",
  familyOrder: ["sum", "worst", "constraint", "threshold", "lexical", "plural", "procedure", "commitment"],
  skepticFamily: "commitment",
  defaultResultTitle: "Your comparisons used more than one way of handling value conflict.",
  skepticTitle: "You ended by choosing a practical settlement without claiming one objectively correct ranking.",
  leadingTitle: (familyId) => `${window.CASE_LAB_CONFIG.families[familyId].name} carried most of your comparisons.`,
  families: {
    sum: { index: "01", name: "Common-scale total", short: "Translate relevant effects onto one scale and choose the option with the best total.", theory: "Aggregation or maximization", note: "Benefits and burdens are compared by a shared unit such as welfare, preference satisfaction, resources, or risk. The account must justify the unit, interpersonal comparisons, and cases where many tiny benefits outweigh one grave loss." },
    worst: { index: "02", name: "Priority to the worse off", short: "Give extra weight to people facing the gravest condition instead of simply adding every effect.", theory: "Priority or maximin-style reasoning", note: "A benefit can matter more when it goes to someone worse off, even if totals are smaller. The view must say how much priority is given and whether a tiny benefit to the worst off can defeat enormous gains elsewhere." },
    constraint: { index: "03", name: "Protected boundary", short: "Some actions remain blocked even when crossing the boundary would improve the overall result.", theory: "Side-constraint or rights-based reasoning", note: "Consent, bodily integrity, promises, and other protections limit what may be done to one person for others. The account must identify the protected boundary and explain whether it survives emergencies." },
    threshold: { index: "04", name: "Boundary with an emergency threshold", short: "Respect a protected rule normally, but allow enough threatened harm to override it.", theory: "Threshold constraint", note: "This preserves ordinary protections without treating them as absolute under catastrophe. The difficult work is fixing a non-arbitrary threshold and explaining why the override does not become ordinary aggregation." },
    lexical: { index: "05", name: "A value that comes first", short: "Protect one kind of value before considering any amount of a lower-ranked value.", theory: "Lexical or discontinuous priority", note: "Life, basic liberty, avoiding torture, or another value may be ranked ahead of comfort, money, or convenience. The account must define categories clearly and handle conflicts between values at the same highest rank." },
    plural: { index: "06", name: "Plural judgment without one master scale", short: "Compare several values in context and accept that no single formula settles every conflict.", theory: "Value pluralism and practical judgment", note: "Reasons can remain distinct yet still support a reasoned judgment through salience, fit, precedent, and mutual adjustment. The account must prevent ‘judgment’ from becoming an unexplained preference or an after-the-fact excuse." },
    procedure: { index: "07", name: "Fair decision procedure", short: "Use a process people can defend when the competing values cannot be conclusively ranked.", theory: "Procedural settlement", note: "A lottery, vote, deliberative panel, appeal process, or equal chance can settle action without proving one value greater. The procedure needs fair representation, relevant information, and limits on what a majority may impose." },
    commitment: { index: "08", name: "Chosen settlement without an objective ranking", short: "Adopt and explain a priority for action while denying that the values have one discovered correct order.", theory: "Non-realist commitment or negotiation", note: "People can choose, negotiate, and revise a settlement because decisions still must be made. The account must own the role of power and commitment, explain why the settlement is defensible, and avoid presenting choice as discovered moral truth." },
  },
  familyChoices: [
    { family: "sum", label: "Put every relevant benefit and burden on one common scale, then choose the best total", detail: "Estimate the size, probability, duration, and number of every effect using one stated unit, and select the option with the greatest net result.", establishes: "A transparent common scale can make the competing effects comparable in this case.", limit: "The answer must defend the unit and explain why adding effects does not erase distribution, consent, separateness of persons, or values the unit omits." },
    { family: "worst", label: "Give extra priority to whoever would otherwise face the most serious condition", detail: "Compare who is worst off under each option and treat a benefit to that person as more important than an equal-sized benefit to someone better off.", establishes: "Distribution and the position of the worst-off party can matter beyond the total result.", limit: "The answer must state how strong the priority is and whether small gains to the worst off can outweigh extremely large gains for everyone else." },
    { family: "constraint", label: "Treat the protected boundary as a limit that a better total result cannot cross", detail: "Identify a rule such as consent, bodily integrity, promise-keeping, or non-sacrifice and remove forbidden options before comparing the remaining outcomes.", establishes: "A protection for individuals can constrain aggregation in the stated conflict.", limit: "The answer must justify the boundary, identify who holds it, and explain what happens if respecting it permits disaster or competing boundaries conflict." },
    { family: "threshold", label: "Protect the boundary unless the threatened harm becomes severe enough to override it", detail: "Apply a consent, promise, liberty, or non-harm rule in ordinary cases, then permit an exception only after a stated emergency threshold is crossed.", establishes: "The case can combine a real protection with a limited outcome-sensitive exception.", limit: "The answer must identify the threshold without tailoring it to the preferred verdict and explain what comparisons determine when it is reached." },
    { family: "lexical", label: "Rank one kind of value first, and compare lower values only after that value is secured", detail: "Give a category such as life, basic liberty, or freedom from extreme suffering priority that no amount of money, convenience, or mild benefit can outweigh.", establishes: "A discontinuous ranking can block trades between importantly different categories here.", limit: "The answer must define the categories, settle conflicts within the top category, and explain why enough lower-ranked effects can never become decisive." },
    { family: "plural", label: "Use several distinct values and make a case-specific judgment without forcing one master scale", detail: "Keep welfare, fairness, consent, loyalty, achievement, and other reasons separate, then explain how their pattern supports a contextual all-things-considered choice.", establishes: "Reasoned comparison may be possible without reducing every value to one quantity.", limit: "The answer must show what disciplines the judgment, permits criticism, and distinguishes a genuine comparison from an unexplained personal reaction." },
    { family: "procedure", label: "Use a fair decision procedure because the competing values do not yield one clear ranking", detail: "Let informed parties use a defensible process such as equal chances, representation, deliberation, voting, reasons, review, and appeal to settle what will be done.", establishes: "A legitimate procedure can settle action when substantive comparison remains incomplete.", limit: "The answer does not prove the winning option better and must protect excluded, outvoted, future, or otherwise weak parties from procedural abuse." },
    { family: "commitment", label: "Choose and defend a practical priority without claiming that one objectively correct ranking exists", detail: "State the values and people you are committing to, negotiate where possible, acknowledge power, and leave the settlement open to criticism and revision.", establishes: "Action can be guided by an explicit non-realist commitment even without a discovered common measure.", limit: "The answer must explain why others should accept or negotiate with the settlement and cannot use ‘no objective ranking’ to hide coercion or avoid giving reasons." },
  ],
  opening: {
    axis: "Your starting comparison rule", prompt: "Before the cases, what can make one choice better supported when important values conflict?",
    context: "A value conflict occurs when one available action protects or advances something important while setting back something else important. ‘Better supported’ asks how the comparison is made, not whether the values are objective facts.",
    assumptions: "For this exercise, objective moral facts and a universal measuring unit are not assumed. You may still select a common scale, protected rule, public procedure, or explicit commitment if you can explain it.",
    scope: "Choose the closest general method. The cases will hold outcomes fixed and test whether you use the same form of comparison across different conflicts.", why: "This records your starting method without adding it to the seven-case bars.",
    guide: { plain: "When two important things cannot both be protected, what makes a decision more than a guess?", separate: "Deciding what to do differs from proving that every value has one true numerical rank.", reveal: "Your answer states the comparison method you expect to use before the cases test it." },
  },
  final: {
    axis: "Your final comparison rule", prompt: "After the cases, what can make one choice better supported when important values conflict?",
    context: "Return to the same question: what warrants a comparison when an option protects one real concern by setting back another?",
    assumptions: "The cases did not prove that values are commensurable, incomparable, objective, or merely chosen. They showed which comparison rules you used under fixed tradeoffs.",
    scope: "Choose the closest general method now. A change from the opening answer is recorded as revision, and using several methods may be a deliberate layered view.", why: "The repeated question shows whether the cases changed or clarified your comparison rule.",
    guide: { plain: "What now seems able to justify a hard tradeoff?", separate: "A settlement can guide action without proving that the losing value was less valuable in every respect.", reveal: "The result compares this final method with the exact rule selected in each case." },
  },
  cases: [
    {
      id: "headaches", phase: "Many small benefits versus one grave loss", axis: "Case — the city of clear mornings", prompt: "Which rule should compare one permanent loss of sight with one million mild headaches?",
      context: "A city can activate a weather shield that prevents exactly one million residents from having one mild, four-hour headache each. Activation will certainly and permanently blind one identified technician through an unavoidable beam. Nobody will die, the headaches cause no missed work or lasting effect, and the technician does not consent. Leaving the shield off preserves the technician’s sight and allows the headaches.",
      assumptions: "All probabilities are certain. The headaches cannot be redistributed or made worse. No compensation, alternate technician, future precedent, hidden benefit, or technological third option exists.",
      scope: "Ask what comparison rule should govern the fixed choice. Do not change the numbers or decide by imagining extra legal, emotional, or political effects.", facts: ["Headaches: 1,000,000 mild", "Blindness: 1 permanent", "Consent: refused", "Other effects: none"],
      why: "Many tiny benefits versus one grave burden tests aggregation, boundaries, and category priority.", guide: { plain: "Can enough small comforts outweigh one person’s permanent blindness?", separate: "The number of beneficiaries and the seriousness of each benefit are different parts of the comparison.", reveal: "Your answer shows whether totals, individual protection, the worst-off person, or a value category controls." },
      applications: { sum: "Place the million headache-hours and the technician’s permanent blindness on the same welfare scale, then compare the total.", worst: "Give strong priority to the technician because blindness leaves that person far worse off than anyone with a mild headache.", constraint: "Refused bodily harm blocks activating the shield even if the sum of small benefits is larger.", threshold: "Protect the technician unless the accumulated headaches cross a stated emergency threshold; mild temporary pain may never reach it.", lexical: "Sight or bodily integrity ranks above mild comfort, so the headaches are considered only after that higher value is secured.", plural: "Consider welfare, distribution, consent, severity, and numbers without assuming that one numerical unit exhausts their importance.", procedure: "Use a process that represents the technician as more than one vote among a million and publicly fixes the protection rule.", commitment: "Choose whether this community will protect individuals from sacrifice for mass convenience, without claiming a discovered numerical answer." },
    },
    {
      id: "scan", phase: "Security versus privacy", axis: "Case — the transparent hour", prompt: "Which rule should compare universal memory privacy with preventing a serious but non-catastrophic attack?",
      context: "Police can prevent a bombing that will certainly injure twenty people by scanning the private memories of every adult for one hour. The scan reveals intimate but lawful thoughts to a secure machine; no human sees them, the data is destroyed, and nobody suffers lasting psychological harm. Ten million adults refuse consent. There is no other way to identify the bomber in time.",
      assumptions: "The attack and prevention are certain. Injuries require hospital care but cause no death or permanent disability. The scan cannot be narrowed, abused later, copied, or turned into precedent.",
      scope: "Ask what rule compares the fixed privacy invasion with the twenty injuries. Do not add distrust, mission creep, false positives, or future surveillance effects.", facts: ["People scanned: 10,000,000", "Consent: refused", "Injuries prevented: 20 serious", "Data: machine-only, destroyed"],
      why: "A broad but temporary invasion tests whether privacy is summed, protected, thresholded, or procedurally governed.", guide: { plain: "May everyone’s private memory be searched to stop twenty serious injuries?", separate: "The intrusion is widespread but temporary; the prevented harms are fewer but physically serious.", reveal: "Your answer locates privacy within totals, boundaries, thresholds, plural judgment, or public authority." },
      applications: { sum: "Compare the total disvalue of ten million one-hour privacy intrusions with the total harm of twenty serious injuries.", worst: "Ask whether the injured victims or the most burdened scanned person would occupy the worse position under each option.", constraint: "Nonconsensual access to thought is a protected boundary that the promised outcome cannot cross.", threshold: "Memory privacy holds normally but may yield if twenty serious injuries exceed a publicly stated emergency threshold.", lexical: "Mental privacy ranks ahead of preventing nonfatal injury, or physical security ranks first; the chosen top category settles the case.", plural: "Treat privacy, bodily safety, consent, scope, severity, and certainty as distinct reasons requiring contextual judgment.", procedure: "A prior constitutional and representative procedure should decide whether this narrowly specified emergency power is legitimate.", commitment: "Adopt and defend a political priority between mental privacy and security without presenting the choice as an objective ranking." },
    },
    {
      id: "promise", phase: "A promise versus lives", axis: "Case — the last return capsule", prompt: "Which rule should compare a precise rescue promise with saving five additional strangers?",
      context: "Before a mission, Commander Sol promised engineer Yara: ‘If only one return capsule remains, it is yours.’ A collision leaves one capsule. Giving it to Yara keeps the promise and strands five unpromised researchers, who die. Giving it to the five breaks the voluntary, informed promise and strands Yara, who dies. Everyone has an equal chance of a normal life if rescued; no lottery or shared ride is possible.",
      assumptions: "Sol made the promise freely and Yara relied on it by accepting the mission. Sol did not promise anyone else. The five are not responsible for the collision, and no future trust or precedent is affected.",
      scope: "Ask what rule compares keeping this promise with saving the five. Do not add special skills, family ties, future social benefits, or blame.", facts: ["Promise: precise and relied on", "Saved if kept: 1", "Saved if broken: 5", "Other effects: none"],
      why: "A clean promise-versus-lives case tests whether constraints are absolute, thresholded, or outweighed.", guide: { plain: "Does a serious promise survive when breaking it saves five instead of one?", separate: "The promise is a genuine reason even if another reason ultimately wins.", reveal: "Your answer shows whether numbers, personal commitment, individual boundaries, or a threshold controls." },
      applications: { sum: "Count the five additional lives saved as a larger total benefit than preserving the one promised rescue.", worst: "Everyone faces death if left behind, so priority alone may not distinguish them; numbers or another reason must break the tie.", constraint: "Yara’s relied-upon promise blocks using her capsule for others despite the better total outcome.", threshold: "The promise normally binds, but five otherwise preventable deaths may cross the stated emergency threshold.", lexical: "Preserving life ranks first; because lives are at the same rank, a secondary rule such as number, promise, or chance is still needed.", plural: "Weigh reliance, voluntary assurance, five lives, equal prospects, and Sol’s special relation without reducing them to one unit.", procedure: "A mission rule chosen in advance by all participants should determine whether promises, numbers, or a lottery governs scarce rescue.", commitment: "Sol or the mission must own a chosen priority between promise and number while acknowledging that the loss cannot be made value-free." },
    },
    {
      id: "archive", phase: "Unique culture versus health", axis: "Case — the library that cannot be copied", prompt: "Which rule should compare an irreplaceable cultural archive with preventing treatable illness?",
      context: "A desert community possesses the only archive of a vanished language: ten thousand fragile recordings that cannot be copied before a coming flood. The sole rescue vehicle can either move the archive or deliver medicine that prevents two thousand residents from suffering a painful but fully temporary seven-day illness. Nobody dies or has lasting injury. If the archive is lost, no living speaker, descendant, researcher, or future project depends on it, but a unique human achievement disappears forever.",
      assumptions: "The archive has no market value and its loss causes no personal grief beyond valuing the achievement itself. The illness has no economic or long-term effect. A split trip or later recovery is impossible.",
      scope: "Ask how to compare unique cultural value with temporary welfare. Do not turn the archive into hidden tourism, identity, scientific, or property benefits.", facts: ["Archive: unique, unrecoverable", "Illness: 2,000 people, 7 days", "Lasting medical harm: none", "Hidden users: none"],
      why: "A unique achievement and temporary suffering resist an obvious common measuring unit.", guide: { plain: "Can something irreplaceable outweigh a large amount of temporary pain even when nobody needs it?", separate: "Uniqueness does not itself state how much weight the archive receives.", reveal: "Your answer shows whether cultural and welfare values are aggregated, ranked, judged plurally, or settled." },
      applications: { sum: "Assign both preserved cultural value and avoided pain a common unit, then select the larger net total.", worst: "Give priority to the sick residents as the only people who endure a serious personal burden under either option.", constraint: "If access to needed medicine is protected, the archive cannot displace it; if heritage is protected, specify whose boundary it is.", threshold: "Preserve the archive normally, but allow enough severe human suffering to cross a stated health threshold—or reverse that default.", lexical: "Place basic health or irreplaceable human achievement first and let that category control before lower-ranked effects are counted.", plural: "Keep cultural achievement, irreversibility, pain, numbers, and human welfare distinct while explaining the case-specific balance.", procedure: "Let an informed, representative process decide who may speak for future cultural loss and present patients.", commitment: "The community can choose what kind of loss it will bear and state that priority without claiming a universal objective conversion rate." },
    },
    {
      id: "medicine", phase: "Totals versus the worst off", axis: "Case — the divisible silver dose", prompt: "Which rule should compare saving one person in immediate danger with helping forty people who are less ill?",
      context: "A medicine can be given as one full dose to Ren, who otherwise dies tonight, producing a certain cure. Or it can be divided into forty smaller doses that each cure a different patient’s severe six-month illness; all forty otherwise recover fully after six months and none will die. Ren has enjoyed a normal life and the forty are not responsible for their illness. No partial dose helps Ren.",
      assumptions: "Every outcome is certain. Pain levels, recovery dates, ages, resources, relationships, and future contributions are otherwise equal. There is no lottery time, extra supply, or way to compensate the losing side.",
      scope: "Ask which comparison rule governs one death against forty severe but temporary illnesses. Do not add social worth, deservingness, or uncertainty.", facts: ["Full dose: 1 life saved", "Split dose: 40 cures", "Other patients: recover in 6 months", "Outcomes: certain"],
      why: "A grave claim and a larger total benefit test priority, lexical value, and aggregation.", guide: { plain: "Should one life receive the medicine instead of forty long but nonfatal cures?", separate: "Saving the worst-off person and producing the greatest total health are different rules.", reveal: "Your answer shows how severity, number, and value categories interact." },
      applications: { sum: "Convert Ren’s avoided death and forty avoided six-month illnesses into one health or welfare total and compare them.", worst: "Give extra priority to Ren because death is the gravest individual outcome, even if forty people receive less total benefit.", constraint: "A claim against being allowed to die may constrain division, but the account must identify why Ren holds the dose rather than the group.", threshold: "Protect the life-saving use unless the number or severity of other illnesses crosses a stated override threshold.", lexical: "Saving a life ranks before curing nonfatal illness, so Ren receives the dose regardless of the forty lower-ranked benefits.", plural: "Compare death, severe pain, duration, number, and fair access without assuming a single health unit settles every feature.", procedure: "Use a prospectively accepted allocation rule, with representation and appeal, when substantive reasons remain contested.", commitment: "Adopt and publicly defend a priority for life-saving or wider relief without claiming an objectively required conversion." },
    },
    {
      id: "talents", phase: "Different forms of loss", axis: "Case — two unfinished lives", prompt: "Which rule should compare losses that transform two people’s lives in different ways?",
      context: "One treatment can prevent either Ada, a devoted violinist, from permanently losing all hearing or Bo, a devoted runner, from permanently losing all leg movement. Each is twenty-five, experiences the threatened ability as central to a carefully chosen life, can build a worthwhile but very different life after the loss, and rates their own threatened loss as maximally serious. Medical burden and probability are identical.",
      assumptions: "Neither person is famous, dependent on the talent for income, responsible for the condition, or more socially useful. No neutral expert can show that one loss produces more pain, lost opportunity, or adaptation difficulty.",
      scope: "Ask what rule should settle between unlike but equally central losses. Do not assume hearing or mobility has an obvious universal numerical rank.", facts: ["Hearing loss: total", "Mobility loss: total", "Personal centrality: equal", "Measured burden: tied"],
      why: "Different life-shaping losses test parity, incomparability, and the role of fair procedure.", guide: { plain: "How should we choose when two losses are deeply serious in different ways and every measured factor ties?", separate: "A lack of one greater value need not mean that no reasoned or fair decision is possible.", reveal: "Your answer shows whether you create a scale, rank a category, judge context, use chance, or choose a commitment." },
      applications: { sum: "Use the common measures that remain; because every stipulated total ties, aggregation alone may require a lottery or added unit.", worst: "Both are equally badly placed under the fixed comparison, so priority produces a tie that needs another rule.", constraint: "Each holds an equal protection against avoidable life-changing loss, leaving a conflict of constraints that needs resolution.", threshold: "Both losses cross the same threshold, so the threshold rule identifies seriousness but does not choose between them.", lexical: "If hearing and mobility occupy the same highest category, lexical ranking also needs a secondary rule.", plural: "Recognize the losses as different yet possibly on a par, then use contextual reasons without pretending one is simply greater.", procedure: "Give Ada and Bo equal chances through a transparent lottery because the substantive claims remain tied.", commitment: "Choose or negotiate a settlement while explicitly denying that the facts contain one uniquely correct ranking." },
    },
    {
      id: "harbor", phase: "Several values across groups", axis: "Case — the harbor that moves inland", prompt: "Which rule should compare work, home, local self-rule, and the survival of a nonhuman habitat?",
      context: "A town can build a seawall that preserves eight thousand secure jobs and every resident’s home for fifty years. The wall will certainly destroy the only breeding marsh of a conscious bird species, causing ten thousand birds painful deaths and eliminating the species. The alternative relocates the town safely inland: nobody is homeless or killed, but all jobs end, each resident loses a chosen home and local way of life, and the birds survive. Residents vote 82% for the wall.",
      assumptions: "Compensation covers basic material needs after relocation but cannot restore jobs, place, or community history. The birds are certainly sentient. No third design, future ecological effect, or uncertainty exists.",
      scope: "Ask what comparison rule should govern the stated human and animal claims. Do not decide the case merely by the vote or assume that every value fits money.", facts: ["Human community: 8,000 jobs and homes", "Bird deaths: 10,000 painful", "Species loss: certain", "Local vote: 82% for wall"],
      why: "A multi-party conflict tests totals, standing, irreversible loss, democratic settlement, and explicit commitment together.", guide: { plain: "How should a community compare its jobs and homes with many animal deaths and extinction?", separate: "A majority vote can authorize policy without proving that every affected claim was given the right weight.", reveal: "Your answer shows how your method handles unlike values, nonvoters, and irreversible loss." },
      applications: { sum: "Place human work, home, community, bird suffering, and extinction on one stated scale and choose the better total.", worst: "Identify who is worst off under each option and give extra priority to death, severe suffering, or the deepest human displacement.", constraint: "Treat avoidable killing, destruction of home, or another specified boundary as limiting what the majority may choose.", threshold: "Protect the marsh or town normally, then ask whether the opposing losses cross a clearly stated emergency threshold.", lexical: "Rank life, sentient suffering, basic security, community, or species survival into categories and apply the highest relevant rank first.", plural: "Compare sentient suffering, livelihoods, attachment, democracy, and irreversibility as distinct values through disciplined judgment.", procedure: "Use a broader procedure that represents residents, displaced workers, ecological expertise, and the interests of nonvoting animals.", commitment: "State which human and nonhuman commitments the policy will honor, acknowledge power, and defend the settlement without objective-ranking language." },
    },
  ],
  detectSeams: ({ answers, final, hits }) => {
    const seams = [];
    if (final?.family === "sum" && hits("constraint") + hits("lexical") >= 2) seams.push({ id: "limits-inside-total", title: "Several cases blocked trades inside a final common-scale account", detail: `${hits("constraint") + hits("lexical")} cases used a protected boundary or value that came first, while the final method says to choose the best total. Explain whether those protections receive very large weights or stand outside the scale.` });
    if (final?.family === "constraint" && answers.promise === "sum") seams.push({ id: "promise-override", title: "The rescue promise was aggregated inside a constraint-based final rule", detail: "The last-capsule case used a common total to override Yara’s relied-upon promise. State whether life-saving emergencies defeat the constraint and, if so, where the threshold lies." });
    if (final?.family === "lexical" && answers.talents === "procedure") seams.push({ id: "same-rank-tie", title: "The top-ranked category still needed a settlement rule", detail: "The two unfinished lives case used fair procedure because the values occupied the same level. Your final lexical ranking therefore needs a secondary rule for conflicts within its highest category." });
    if (final?.family === "procedure" && hits("procedure") < 3) seams.push({ id: "procedure-reach", title: "The final procedure appeared less often in the cases", detail: `Only ${hits("procedure")} of seven cases used procedure, while the final answer gives it the general settling role. Clarify when substantive reasons decide first and when the procedure takes over.` });
    if (final?.family === "commitment" && hits("sum") + hits("constraint") + hits("lexical") >= 4) seams.push({ id: "objective-sounding-rules", title: "Several case rules sounded firmer than the final chosen settlement", detail: `${hits("sum") + hits("constraint") + hits("lexical")} cases used a total, constraint, or fixed priority. Explain whether these are adopted commitments, publicly negotiated standards, or claims about an independently correct ranking.` });
    return seams;
  },
  aiPremise: "Suppose objective moral facts and a universal value-measuring unit are not assumed. Ask how a person or community can make defensible comparisons when protecting one important value sets back another.",
  aiCautions: [
    "Keep having a reason, comparing reasons, settling action, and proving one value objectively greater as separate tasks.",
    "Do not invent probabilities, consequences, precedent, compensation, or affected people beyond each fixed case.",
    "Do not assume that using several comparison rules is incoherent; ask for their order, scope, and trigger conditions.",
    "A fair procedure can settle what is done without proving the selected outcome substantively best.",
    "A non-realist commitment still needs transparency about power, affected parties, revision, and why others might accept it.",
  ],
};
